import { Inter } from "next/font/google";
import HeaderNotice from "../(with-layout)/HeaderNotice/HeaderNotice";
import Header from "../(with-layout)/Header/Header";
import GalleryHeader from "./GalleryHeader/GalleryHeader";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <div>
        <Header></Header>
        <div className="mb-8 w-9/12 mx-auto">
          <HeaderNotice></HeaderNotice>
        </div>

        <div>
          <GalleryHeader></GalleryHeader>
          <div className="w-9/12 mx-auto">{children}</div>
        </div>
      </div>
    </>
  );
}
