import { Inter } from "next/font/google";
import Sidebar from "./Sidebar/Sidebar";

const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <div className=" grid grid-cols-5 gap-8  ">
      <div className="col-span-1 bg-gray-100 min-h-screen p-10 ">
        <Sidebar></Sidebar>
      </div>
      <div className="col-span-4 px-8 py-16 ">{children}</div>
    </div>
  );
}
