import { Inter } from "next/font/google";
import Sidebar from "./Sidebar/Sidebar";

const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <div className=" w-11/12 mx-auto py-10 grid grid-cols-5 gap-10">
      <div className="col-span-1">
        <Sidebar></Sidebar>
      </div>
      <div className="col-span-4">{children}</div>
    </div>
  );
}
