import { Inter } from "next/font/google";
import Sidebar from "./Sidebar/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className=" w-11/12 mx-auto py-10 flex gap-10">
      <Sidebar></Sidebar>
      {children}
    </div>
  );
}
